new restaurant resource
matanbanner/weeat pull request #1
Opened 2017-04-19 12:50 UTC by matanbanner

new restaurant resource

2017-04-19 13:43 UTC, omergertel commented on app/models/restaurant.rb
> +class Restaurant < ApplicationRecord
Please add some input validation. Name of restaurant should probably be unique, most of the other inputs also have limitations.

2017-04-19 13:55 UTC, omergertel requested changes
Good start! Using scaffolds was a great way to get a lot done fast. We love to get things done. 

The biggest thing missing is input validations. Could you please add them?

2017-04-19 13:55 UTC, omergertel commented on app/models/restaurant.rb
> +end
Please add some input validation. Name of restaurant should probably be unique, most of the other inputs also have limitations.

2017-04-19 13:55 UTC, omergertel commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :name
Please add some input validation. Name of restaurant should probably be unique, most of the other inputs also have limitations.

2017-04-19 13:55 UTC, omergertel commented on app/views/restaurants/index.html.erb
> +        <td><%= restaurant.name %></td>
The restaurant part should probably be moved to a partial. Think about template structure when doing the next part of the project, to make files easier to read.

2017-04-19 13:55 UTC, omergertel commented on test/controllers/restaurants_controller_test.rb
> +class RestaurantsControllerTest < ActionDispatch::IntegrationTest
This is fine for now. We'll replace tests with rspec in a future task.

2017-04-19 13:55 UTC, omergertel commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :delivery_time
What are the legal values for this field?

2017-04-19 13:55 UTC, omergertel commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :address
What's the structure of an address? Is it just a string, or something more complex (city, street, number)?

2017-04-19 15:48 UTC, matanbanner commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :name
Done

2017-04-19 15:48 UTC, matanbanner commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :address
What's wrong with just String?

2017-04-19 15:49 UTC, matanbanner commented on db/migrate/20170419121747_create_restaurants.rb
> +      t.string :delivery_time
delivery_time is now an integer

2017-04-19 15:51 UTC, matanbanner commented on app/views/restaurants/index.html.erb
> +        <td><%= restaurant.name %></td>
Done

2017-04-20 07:29 UTC, matanbanner commented on app/models/restaurant.rb
> +end
This is also done

2017-04-20 08:14 UTC, omergertel requested changes

2017-04-20 08:14 UTC, omergertel commented on app/models/restaurant.rb
> +  validates :genre, presence: true
Cool. I think we should limit this to a few supported genres (you'd want each genre to match a font icon in the UI), and allow inputing a genre from a drop down.

Do you prefer doing this change in the UI task?

2017-04-20 08:14 UTC, omergertel commented on app/models/restaurant.rb
> +  validates :delivery_time, {presence: true, numericality: { only_integer: true }}
`greater_than_or_equal_to : 0`

2017-04-20 08:14 UTC, omergertel commented on app/models/restaurant.rb
> +end
Sweet!

2017-04-20 08:14 UTC, omergertel commented on db/migrate/20170419153126_retaurant_unique_name.rb
> +    add_index :restaurants, :name, :unique => true
Perfect!

2017-04-20 08:14 UTC, omergertel commented on app/views/restaurants/_restaurants.erb
> +<table>
This is not exactly what I was talking about. I was talking about the restaurant row.
Think about a restaurant as a component that might be reused more than once.
When you add reviews or other information, and have a restaurant page (`#show`), you could then reuse the `_restaurant.erb`.
This is something to keep in mind when you do the UI task, no reason to change the UI any further in this PR since you'll rewrite it shortly.

2017-04-27 11:44 UTC, omergertel approved these changes

2017-04-27 11:44 UTC, omergertel approved these changes

2017-04-27 11:44 UTC, merged